# Generated by Django 4.2.7 on 2023-12-02 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
