# Generated by Django 4.2.7 on 2023-12-01 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_paymentelement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="invoice",
        ),
    ]
