# Generated by Django 4.2.7 on 2023-12-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_payment_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
