# Generated by Django 4.2.11 on 2025-02-15 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_delete_serialul"),
        ("payments", "0002_payment_cancellation_to_payment_cancelled_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="services.currency",
            ),
        ),
    ]
