# Generated by Django 4.2.7 on 2023-12-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_alter_payment_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentelement",
            name="value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
