# Generated by Django 4.2.11 on 2025-02-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="is_recurrent",
            field=models.BooleanField(default=False),
        ),
    ]
