# Generated by Django 4.2.7 on 2023-12-05 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_paymentelement_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentelement",
            name="value",
        ),
    ]
