# Generated by Django 4.2.11 on 2025-12-18 11:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "invoices",
            "0007_alter_invoice_deadline_alter_invoiceelement_element_and_more",
        ),
        ("payments", "0006_payment_vat_rate_payment_vat_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="paymentelement",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_links",
                to="invoices.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="paymentelement",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elements",
                to="payments.payment",
            ),
        ),
    ]
