# Generated by Django 4.2.6 on 2023-11-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pictures/my-profile-default.jpg",
                upload_to="profile_pictures/",
            ),
        ),
    ]
