# Generated by Django 4.2.6 on 2023-11-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(default="success", upload_to="profile_pictures/"),
            preserve_default=False,
        ),
    ]
