# Generated by Django 4.2.11 on 2025-02-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_serialul"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Serialul",
        ),
    ]
