# Generated by Django 4.2.11 on 2024-09-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="comments",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
