# Generated by Django 4.2.7 on 2023-11-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_client",
            field=models.BooleanField(default=True),
        ),
    ]
