# Generated by Django 4.2.11 on 2024-09-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_invoice_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="comments",
        ),
        migrations.AddField(
            model_name="invoice",
            name="is_recurrent",
            field=models.BooleanField(default=False),
        ),
    ]
