# Generated by Django 4.2.7 on 2023-11-23 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0002_invoice_is_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceelement",
            name="description",
        ),
    ]
