# Generated by Django 4.2.11 on 2025-02-15 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_delete_serialul"),
        ("invoices", "0003_remove_invoice_comments_invoice_is_recurrent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="services.currency",
            ),
        ),
        migrations.AlterField(
            model_name="proforma",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="services.currency",
            ),
        ),
    ]
