# Generated by Django 4.2.6 on 2023-11-15 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0003_invoiceelement_invoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="order",
        ),
    ]
