# Generated by Django 4.2.11 on 2025-12-18 09:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_offer_order_alter_offerelement_offer_and_more"),
        (
            "invoices",
            "0006_invoice_vat_rate_invoice_vat_value_proforma_vat_rate_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="deadline",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="invoiceelement",
            name="element",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_links",
                to="orders.orderelement",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceelement",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elements",
                to="invoices.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="proforma",
            name="deadline",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="proforma",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proformas",
                to="invoices.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="proformaelement",
            name="element",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proforma_links",
                to="orders.orderelement",
            ),
        ),
        migrations.AlterField(
            model_name="proformaelement",
            name="proforma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elements",
                to="invoices.proforma",
            ),
        ),
    ]
