# Generated by Django 4.2.6 on 2023-11-15 06:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0002_remove_receipt_user_receipt_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipt",
            name="currency",
        ),
    ]
