# Generated by Django 4.2.7 on 2023-12-13 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("symbol", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Serial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_serial", models.CharField(blank=True, max_length=10)),
                ("offer_number", models.PositiveIntegerField(default=0)),
                ("order_serial", models.CharField(blank=True, max_length=10)),
                ("order_number", models.PositiveIntegerField(default=0)),
                ("p_order_serial", models.CharField(blank=True, max_length=10)),
                ("p_order_number", models.PositiveIntegerField(default=0)),
                ("proforma_serial", models.CharField(blank=True, max_length=10)),
                ("proforma_number", models.PositiveIntegerField(default=0)),
                ("invoice_serial", models.CharField(blank=True, max_length=10)),
                ("invoice_number", models.PositiveIntegerField(default=0)),
                ("receipt_serial", models.CharField(blank=True, max_length=10)),
                ("receipt_number", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("style", models.CharField(default="success", max_length=25)),
                ("percent", models.SmallIntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name="UM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price_min", models.DecimalField(decimal_places=2, max_digits=8)),
                ("price_max", models.DecimalField(decimal_places=2, max_digits=8)),
                ("icon", models.CharField(max_length=100)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.currency",
                    ),
                ),
                (
                    "um",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="services.um"
                    ),
                ),
            ],
        ),
    ]
