# Generated by Django 4.2.7 on 2023-12-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serial",
            name="offer_number",
            field=models.PositiveIntegerField(
                default=0, verbose_name="positive number"
            ),
        ),
        migrations.AddField(
            model_name="serial",
            name="offer_serial",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="serial",
            name="order_number",
            field=models.PositiveIntegerField(
                default=0, verbose_name="positive number"
            ),
        ),
        migrations.AddField(
            model_name="serial",
            name="order_serial",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="serial",
            name="proforma_number",
            field=models.PositiveIntegerField(
                default=0, verbose_name="positive number"
            ),
        ),
        migrations.AddField(
            model_name="serial",
            name="proforma_serial",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
