# Generated by Django 4.2.11 on 2025-02-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Serialul",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("offer", "Offer"),
                            ("order", "Order"),
                            ("invoice", "Invoice"),
                            ("proforma", "Proforma"),
                            ("receipt", "Receipt"),
                        ],
                        max_length=10,
                    ),
                ),
                ("serial", models.CharField(blank=True, max_length=10)),
                ("number", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
