# Generated by Django 4.2.7 on 2023-11-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Serial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_serial", models.CharField(max_length=10)),
                ("invoice_number", models.IntegerField()),
                ("receipt_serial", models.CharField(max_length=10)),
                ("receipt_number", models.IntegerField()),
            ],
        ),
    ]
