# Generated by Django 4.2.7 on 2023-12-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serial",
            name="p_order_number",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="serial",
            name="p_order_serial",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
