# Generated by Django 4.2.7 on 2023-12-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_serial_offer_number_serial_offer_serial_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serial",
            name="invoice_number",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="serial",
            name="offer_number",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="serial",
            name="order_number",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="serial",
            name="proforma_number",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="serial",
            name="receipt_number",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
