# Generated by Django 4.2.6 on 2023-11-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_status_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="percent",
            field=models.SmallIntegerField(default=20),
        ),
    ]
