# Generated by Django 4.2.7 on 2023-11-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_serial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serial",
            name="invoice_number",
            field=models.PositiveIntegerField(
                default=0, verbose_name="positive number"
            ),
        ),
        migrations.AlterField(
            model_name="serial",
            name="invoice_serial",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="serial",
            name="receipt_number",
            field=models.PositiveIntegerField(
                default=0, verbose_name="positive number"
            ),
        ),
        migrations.AlterField(
            model_name="serial",
            name="receipt_serial",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
