# Generated by Django 4.2.7 on 2023-12-14 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="services.status",
            ),
        ),
    ]
