# Generated by Django 4.2.7 on 2023-12-14 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        ("appointments", "0002_appointment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="order_element",
        ),
        migrations.AddField(
            model_name="appointment",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
            ),
            preserve_default=False,
        ),
    ]
