# Generated by Django 4.2.7 on 2023-12-14 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0001_initial"),
        ("appointments", "0003_remove_appointment_order_element_appointment_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="person",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="person_%(class)s",
                to="persons.person",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="with_person",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="with_person_%(class)s",
                to="persons.person",
            ),
        ),
    ]
