# Generated by Django 4.2.7 on 2023-12-14 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        ("appointments", "0004_alter_appointment_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.order",
            ),
        ),
    ]
