# Generated by Django 4.2.6 on 2023-11-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="services",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
