# Generated by Django 4.2.7 on 2023-11-28 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_alter_serial_invoice_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offerelement",
            old_name="units",
            new_name="quantity",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="to_order",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="user",
        ),
        migrations.RemoveField(
            model_name="offerelement",
            name="currency",
        ),
        migrations.AddField(
            model_name="offer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_by_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="services.currency",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_by_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="services.status",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
