# Generated by Django 4.2.7 on 2023-11-28 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_rename_units_offerelement_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="is_client",
        ),
        migrations.AddField(
            model_name="offer",
            name="order",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.order",
            ),
        ),
    ]
