# Generated by Django 4.2.11 on 2025-02-15 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_delete_serialul"),
        ("orders", "0002_alter_order_currency_alter_orderelement_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="services.currency",
            ),
        ),
        migrations.AlterField(
            model_name="offerelement",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="services.service",
            ),
        ),
        migrations.AlterField(
            model_name="offerelement",
            name="um",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="services.um",
            ),
        ),
    ]
