# Generated by Django 4.2.6 on 2023-11-05 07:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
    ]
