# Generated by Django 4.2.11 on 2025-03-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_offer_currency_alter_offerelement_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="is_client",
            field=models.BooleanField(default=True),
        ),
    ]
