# Generated by Django 4.2.11 on 2025-03-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_offer_is_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoiced",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
