# Generated by Django 4.2.11 on 2025-12-18 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_offer_vat_rate_offer_vat_value_order_vat_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offerelement",
            name="quantity",
            field=models.SmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="orderelement",
            name="quantity",
            field=models.SmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
