# Generated by Django 4.2.11 on 2025-12-18 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_offerelement_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="order",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offers",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="offerelement",
            name="offer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elements",
                to="orders.offer",
            ),
        ),
        migrations.AlterField(
            model_name="orderelement",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elements",
                to="orders.order",
            ),
        ),
    ]
